import json

# Dicionário 
dados = {
    "olimpico engenhao": "nilton santos",
    "engenhao": "nilton santos",
    "arena corinthians": "neo quimica arena",
    "neo quimica arena": "neo quimica arena",
    "municipal paulo machado de carvalho": "pacaembu",
    "urbano caldeira": "vila belmiro",
    "jose pinheiro borda": "beira-rio",
    "beira rio": "beira-rio",
    "arena castelao": "castelao",
    "placido castelo": "castelao",
    "castelao de sao luis": "castelao",
    "parque antartica": "allianz parque",
    "palestra italia": "allianz parque",
    "itaipava arena fonte nova": "fonte nova",
    "arena fonte nova": "fonte nova",
    "da serrinha": "serrinha",
    "adelmar da costa carvalho": "ilha do retiro",
    "raimundo sampaio": "independencia",
    "do governo do estado de goias (serra dourada)": "serra dourada",
    "nabizao": "nabi abi chedid",
    "kyocera arena": "ligga arena",
    "arena da baixada": "ligga arena",
    "joaquim americo guimaraes": "ligga arena",
    "municipal general raulino de oliveira": "raulino de oliveira",
    "haile pinheiro - serrinha" : "serrinha",
    "do vale": "estadio do vale",
    "claudio moacyr": "claudio moacyr de azevedo",
    "municipal parque do sabia": "parque do sabia",
    "moacyrzao": "claudio moacyr de azevedo",
    "do cafe": "estadio do cafe",
    "alberto oliveira": "joia da princesa",
    "vasco da gama": "sao januario",
    "doutor adhemar de barros": "fonte luminosa",
    "santa cruz": "arruda",
    "benedito teixeira": "teixeirao",
    "melao": "estadio do melao",
    "pres vargas": "presidente vargas",
    "mario helenio": "helenao",
    "batistao": "arena batistao",
    "romildao": "vail chaves",
    "wilson de barros": "vail chaves",
    "eduardo jose farah": "prudentao",
    "g coutinho": "giulite coutinho",
    "bruno j daniel ": "bruno jose daniel",
    "mj jose levi sobrinho": "limeirao",
    "pedro pedrossian": "morenao",
    "vivaldo lima": "arena da amazonia",
    "edson passos": "giulite coutinho",
    "municipal juiz de fora": "helenao",
    "a campanella": "anacleto campanella",
    "bruno j.daniel": "bruno jose daniel",
    "bruno j daniel": "bruno jose daniel",
    "luiz lacerda": "lacerdao",
    "r de oliveira": "raulino de oliveira",
    "serejao": "boca do jacare",
    "a.campanella": "anacleto campanella",
    "papa joao paulo ii": "vail chaves",
    "papa j.paulo ii": "vail chaves",
    "municipal juscelino kubitschek": "juscelino kubitscheck",
    "juiz de fora":"helenao",
    "romildo ferreira": "vail chaves",
    "paulo constantino": "prudentao",
    "joaquim henrique nogueira-arena do jacare": "arena do jacare",
    "luso-brasileiro": "luso brasileiro",
    "arena brb mane garrincha": "mane garrincha",
    "bruno josé daniel": "bruno jose daniel",
    "de pituacu": "pituacu",
    "texeirao": "teixeirao",
    "arena de pernambuco": "arena pernambuco",
    "arena da amazonia":"arena amazonia",
    "nacional de brasilia": "mane garrincha",
    "durival de brito": "vila capanema"
    }

arquivo = r'C:\Users\USER\Desktop\GitHub\Brasileirao-Analise\3. Source Code\Transformed\arenas_dict.json'
# Salvando em arquivo
with open(arquivo, 'w', encoding='utf-8') as f:
    json.dump(dados, f, indent=2, ensure_ascii=False)

print("Dicionário JSON criado e salvo com sucesso!")
